///************************************************
/// Generated by: tinhth
/// Date: 20/09/2011 04:39:17
/// Goal: Create User Service Class for GD_LOP_MON_DETAIL
///************************************************
/// <summary>
/// Create User Service Class for GD_LOP_MON_DETAIL
/// </summary>

using System;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;
using WebDS;


namespace WebUS{

public class US_GD_LOP_MON_DETAIL : US_Object
{
	private const string c_TableName = "GD_LOP_MON_DETAIL";
#region "Public Properties"
	public decimal dcID 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID"] = value;
		}
	}

	public bool IsIDNull()	{
		return pm_objDR.IsNull("ID");
	}

	public void SetIDNull() {
		pm_objDR["ID"] = System.Convert.DBNull;
	}

	public decimal dcID_LOP_MON 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_LOP_MON", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_LOP_MON"] = value;
		}
	}

	public bool IsID_LOP_MONNull()	{
		return pm_objDR.IsNull("ID_LOP_MON");
	}

	public void SetID_LOP_MONNull() {
		pm_objDR["ID_LOP_MON"] = System.Convert.DBNull;
	}

	public decimal dcID_HOP_DONG_KHUNG 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_HOP_DONG_KHUNG", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_HOP_DONG_KHUNG"] = value;
		}
	}

	public bool IsID_HOP_DONG_KHUNGNull()	{
		return pm_objDR.IsNull("ID_HOP_DONG_KHUNG");
	}

	public void SetID_HOP_DONG_KHUNGNull() {
		pm_objDR["ID_HOP_DONG_KHUNG"] = System.Convert.DBNull;
	}

	public decimal dcID_NOI_DUNG_THANH_TOAN 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_NOI_DUNG_THANH_TOAN", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_NOI_DUNG_THANH_TOAN"] = value;
		}
	}

	public bool IsID_NOI_DUNG_THANH_TOANNull()	{
		return pm_objDR.IsNull("ID_NOI_DUNG_THANH_TOAN");
	}

	public void SetID_NOI_DUNG_THANH_TOANNull() {
		pm_objDR["ID_NOI_DUNG_THANH_TOAN"] = System.Convert.DBNull;
	}

	public string strDA_THANH_TOAN_YN 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "DA_THANH_TOAN_YN", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["DA_THANH_TOAN_YN"] = value;
		}
	}

	public bool IsDA_THANH_TOAN_YNNull() 
	{
		return pm_objDR.IsNull("DA_THANH_TOAN_YN");
	}

	public void SetDA_THANH_TOAN_YNNull() {
		pm_objDR["DA_THANH_TOAN_YN"] = System.Convert.DBNull;
	}

	public decimal dcSO_LUONG_HE_SO 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "SO_LUONG_HE_SO", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["SO_LUONG_HE_SO"] = value;
		}
	}

	public bool IsSO_LUONG_HE_SONull()	{
		return pm_objDR.IsNull("SO_LUONG_HE_SO");
	}

	public void SetSO_LUONG_HE_SONull() {
		pm_objDR["SO_LUONG_HE_SO"] = System.Convert.DBNull;
	}

	public decimal dcTHANH_TIEN 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "THANH_TIEN", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["THANH_TIEN"] = value;
		}
	}

	public bool IsTHANH_TIENNull()	{
		return pm_objDR.IsNull("THANH_TIEN");
	}

	public void SetTHANH_TIENNull() {
		pm_objDR["THANH_TIEN"] = System.Convert.DBNull;
	}

#endregion
#region "Init Functions"
	public US_GD_LOP_MON_DETAIL() 
	{
		pm_objDS = new DS_GD_LOP_MON_DETAIL();
		pm_strTableName = c_TableName;
		pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
	}

	public US_GD_LOP_MON_DETAIL(DataRow i_objDR): this()
	{
		this.DataRow2Me(i_objDR);
	}

	public US_GD_LOP_MON_DETAIL(decimal i_dbID) 
	{
		pm_objDS = new DS_GD_LOP_MON_DETAIL();
		pm_strTableName = c_TableName;
		IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
		v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
		SqlCommand v_cmdSQL;
		v_cmdSQL = v_objMkCmd.getSelectCmd();
		this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
		pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
	}
#endregion
	}
}
