///************************************************
/// Generated by: TuDM
/// Date: 28/07/2013 09:42:15
/// Goal: Create User Service Class for GD_DE_NGHI_TRANG_CAP_DETAILS
///************************************************
/// <summary>
/// Create User Service Class for GD_DE_NGHI_TRANG_CAP_DETAILS
/// </summary>

using System;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;
using WebDS;


namespace WebUS{

public class US_GD_DE_NGHI_TRANG_CAP_DETAILS : US_Object
{
	private const string c_TableName = "GD_DE_NGHI_TRANG_CAP_DETAILS";
#region "Public Properties"
	public decimal dcID 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID"] = value;
		}
	}

	public bool IsIDNull()	{
		return pm_objDR.IsNull("ID");
	}

	public void SetIDNull() {
		pm_objDR["ID"] = System.Convert.DBNull;
	}

	public string strMA_PHIEU 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "MA_PHIEU", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["MA_PHIEU"] = value;
		}
	}

	public bool IsMA_PHIEUNull() 
	{
		return pm_objDR.IsNull("MA_PHIEU");
	}

	public void SetMA_PHIEUNull() {
		pm_objDR["MA_PHIEU"] = System.Convert.DBNull;
	}

	public decimal dcID_LOAI_TAI_SAN 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_LOAI_TAI_SAN", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_LOAI_TAI_SAN"] = value;
		}
	}

	public bool IsID_LOAI_TAI_SANNull()	{
		return pm_objDR.IsNull("ID_LOAI_TAI_SAN");
	}

	public void SetID_LOAI_TAI_SANNull() {
		pm_objDR["ID_LOAI_TAI_SAN"] = System.Convert.DBNull;
	}

	public decimal dcSO_LUONG 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "SO_LUONG", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["SO_LUONG"] = value;
		}
	}

	public bool IsSO_LUONGNull()	{
		return pm_objDR.IsNull("SO_LUONG");
	}

	public void SetSO_LUONGNull() {
		pm_objDR["SO_LUONG"] = System.Convert.DBNull;
	}

	public decimal dcID_DON_VI_TINH 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_DON_VI_TINH", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_DON_VI_TINH"] = value;
		}
	}

	public bool IsID_DON_VI_TINHNull()	{
		return pm_objDR.IsNull("ID_DON_VI_TINH");
	}

	public void SetID_DON_VI_TINHNull() {
		pm_objDR["ID_DON_VI_TINH"] = System.Convert.DBNull;
	}

	public decimal dcID_PHUONG_THUC 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_PHUONG_THUC", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_PHUONG_THUC"] = value;
		}
	}

	public bool IsID_PHUONG_THUCNull()	{
		return pm_objDR.IsNull("ID_PHUONG_THUC");
	}

	public void SetID_PHUONG_THUCNull() {
		pm_objDR["ID_PHUONG_THUC"] = System.Convert.DBNull;
	}

	public decimal dcDU_TOAN 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "DU_TOAN", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["DU_TOAN"] = value;
		}
	}

	public bool IsDU_TOANNull()	{
		return pm_objDR.IsNull("DU_TOAN");
	}

	public void SetDU_TOANNull() {
		pm_objDR["DU_TOAN"] = System.Convert.DBNull;
	}

	public decimal dcDU_TOAN_DUOC_DUYET 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "DU_TOAN_DUOC_DUYET", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["DU_TOAN_DUOC_DUYET"] = value;
		}
	}

	public bool IsDU_TOAN_DUOC_DUYETNull()	{
		return pm_objDR.IsNull("DU_TOAN_DUOC_DUYET");
	}

	public void SetDU_TOAN_DUOC_DUYETNull() {
		pm_objDR["DU_TOAN_DUOC_DUYET"] = System.Convert.DBNull;
	}

	public string strMO_TA 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "MO_TA", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["MO_TA"] = value;
		}
	}

	public bool IsMO_TANull() 
	{
		return pm_objDR.IsNull("MO_TA");
	}

	public void SetMO_TANull() {
		pm_objDR["MO_TA"] = System.Convert.DBNull;
	}

	public string strGHI_CHU 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "GHI_CHU", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["GHI_CHU"] = value;
		}
	}

	public bool IsGHI_CHUNull() 
	{
		return pm_objDR.IsNull("GHI_CHU");
	}

	public void SetGHI_CHUNull() {
		pm_objDR["GHI_CHU"] = System.Convert.DBNull;
	}

#endregion
#region "Init Functions"
	public US_GD_DE_NGHI_TRANG_CAP_DETAILS() 
	{
		pm_objDS = new DS_GD_DE_NGHI_TRANG_CAP_DETAILS();
		pm_strTableName = c_TableName;
		pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
	}

	public US_GD_DE_NGHI_TRANG_CAP_DETAILS(DataRow i_objDR): this()
	{
		this.DataRow2Me(i_objDR);
	}

	public US_GD_DE_NGHI_TRANG_CAP_DETAILS(decimal i_dbID) 
	{
		pm_objDS = new DS_GD_DE_NGHI_TRANG_CAP_DETAILS();
		pm_strTableName = c_TableName;
		IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
		v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
		SqlCommand v_cmdSQL;
		v_cmdSQL = v_objMkCmd.getSelectCmd();
		this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
		pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
	}
#endregion
	}
}
