///************************************************
/// Generated by: linhdh
/// Date: 01/03/2012 11:38:36
/// Goal: Create User Service Class for RPT_BAO_CAO_THONG_KE_TRANG_THAI_GIANG_VIEN
///************************************************
/// <summary>
/// Create User Service Class for RPT_BAO_CAO_THONG_KE_TRANG_THAI_GIANG_VIEN
/// </summary>

using System;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;
using WebDS;


namespace WebUS{

public class US_RPT_BAO_CAO_THONG_KE_TRANG_THAI_GIANG_VIEN : US_Object
{
	private const string c_TableName = "RPT_BAO_CAO_THONG_KE_TRANG_THAI_GIANG_VIEN";
#region "Public Properties"
	public decimal dcID 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID"] = value;
		}
	}

	public bool IsIDNull()	{
		return pm_objDR.IsNull("ID");
	}

	public void SetIDNull() {
		pm_objDR["ID"] = System.Convert.DBNull;
	}

	public decimal dcID_DON_VI_QUAN_LY 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_DON_VI_QUAN_LY", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_DON_VI_QUAN_LY"] = value;
		}
	}

	public bool IsID_DON_VI_QUAN_LYNull()	{
		return pm_objDR.IsNull("ID_DON_VI_QUAN_LY");
	}

	public void SetID_DON_VI_QUAN_LYNull() {
		pm_objDR["ID_DON_VI_QUAN_LY"] = System.Convert.DBNull;
	}

	public string strDON_VI_QUAN_LY 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "DON_VI_QUAN_LY", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["DON_VI_QUAN_LY"] = value;
		}
	}

	public bool IsDON_VI_QUAN_LYNull() 
	{
		return pm_objDR.IsNull("DON_VI_QUAN_LY");
	}

	public void SetDON_VI_QUAN_LYNull() {
		pm_objDR["DON_VI_QUAN_LY"] = System.Convert.DBNull;
	}

	public decimal dcID_TRANG_THAI_GIANG_VIEN 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_TRANG_THAI_GIANG_VIEN", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_TRANG_THAI_GIANG_VIEN"] = value;
		}
	}

	public bool IsID_TRANG_THAI_GIANG_VIENNull()	{
		return pm_objDR.IsNull("ID_TRANG_THAI_GIANG_VIEN");
	}

	public void SetID_TRANG_THAI_GIANG_VIENNull() {
		pm_objDR["ID_TRANG_THAI_GIANG_VIEN"] = System.Convert.DBNull;
	}

	public string strTRANG_THAI_GIANG_VIEN 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "TRANG_THAI_GIANG_VIEN", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["TRANG_THAI_GIANG_VIEN"] = value;
		}
	}

	public bool IsTRANG_THAI_GIANG_VIENNull() 
	{
		return pm_objDR.IsNull("TRANG_THAI_GIANG_VIEN");
	}

	public void SetTRANG_THAI_GIANG_VIENNull() {
		pm_objDR["TRANG_THAI_GIANG_VIEN"] = System.Convert.DBNull;
	}

	public decimal dcGV_CHUYEN_MON 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "GV_CHUYEN_MON", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["GV_CHUYEN_MON"] = value;
		}
	}

	public bool IsGV_CHUYEN_MONNull()	{
		return pm_objDR.IsNull("GV_CHUYEN_MON");
	}

	public void SetGV_CHUYEN_MONNull() {
		pm_objDR["GV_CHUYEN_MON"] = System.Convert.DBNull;
	}

	public decimal dcGV_HUONG_DAN 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "GV_HUONG_DAN", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["GV_HUONG_DAN"] = value;
		}
	}

	public bool IsGV_HUONG_DANNull()	{
		return pm_objDR.IsNull("GV_HUONG_DAN");
	}

	public void SetGV_HUONG_DANNull() {
		pm_objDR["GV_HUONG_DAN"] = System.Convert.DBNull;
	}

	public decimal dcGV_HOC_LIEU 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "GV_HOC_LIEU", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["GV_HOC_LIEU"] = value;
		}
	}

	public bool IsGV_HOC_LIEUNull()	{
		return pm_objDR.IsNull("GV_HOC_LIEU");
	}

	public void SetGV_HOC_LIEUNull() {
		pm_objDR["GV_HOC_LIEU"] = System.Convert.DBNull;
	}

#endregion
#region "Init Functions"
	public US_RPT_BAO_CAO_THONG_KE_TRANG_THAI_GIANG_VIEN() 
	{
		pm_objDS = new DS_RPT_BAO_CAO_THONG_KE_TRANG_THAI_GIANG_VIEN();
		pm_strTableName = c_TableName;
		pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
	}

	public US_RPT_BAO_CAO_THONG_KE_TRANG_THAI_GIANG_VIEN(DataRow i_objDR): this()
	{
		this.DataRow2Me(i_objDR);
	}

	public US_RPT_BAO_CAO_THONG_KE_TRANG_THAI_GIANG_VIEN(decimal i_dbID) 
	{
		pm_objDS = new DS_RPT_BAO_CAO_THONG_KE_TRANG_THAI_GIANG_VIEN();
		pm_strTableName = c_TableName;
		IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
		v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
		SqlCommand v_cmdSQL;
		v_cmdSQL = v_objMkCmd.getSelectCmd();
		this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
		pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
	}
#endregion
    #region Additional functions
    public void bao_cao_thong_ke_gv(DS_RPT_BAO_CAO_THONG_KE_TRANG_THAI_GIANG_VIEN op_ds_bao_cao_thong_ke_trang_thai_giang_vien)
    {
        CStoredProc v_cstore = new CStoredProc("rpt_pr_DM_GIANG_VIEN");
        op_ds_bao_cao_thong_ke_trang_thai_giang_vien.EnforceConstraints = false;
        v_cstore.fillDataSetByCommand(this, op_ds_bao_cao_thong_ke_trang_thai_giang_vien);
    }
    #endregion
	}
}
