///************************************************
/// Generated by: TrongHV
/// Date: 28/07/2013 12:21:28
/// Goal: Create Form for V_DM_OTO
///************************************************


using System;
using System.Data;
using System.Drawing;
using System.Collections;
using System.ComponentModel;
using System.Windows.Forms;

using IP.Core.IPCommon;
using IP.Core.IPException;
using IP.Core.IPData;
using IP.Core.IPUserService;
using IP.Core.IPExcelReport;
using IP.Core.IPExcelWebReport;


using WebUS;
using WebDS;
using WebDS.CDBNames;


using C1.Win.C1FlexGrid;

namespace QltsForm {



	public class f400_bao_cao_danh_muc_o_to : System.Windows.Forms.Form
	{
		internal System.Windows.Forms.ImageList ImageList;
		internal System.Windows.Forms.Panel m_pnl_out_place_dm;
		private C1.Win.C1FlexGrid.C1FlexGrid m_fg;
		internal SIS.Controls.Button.SiSButton m_cmd_delete;
		internal SIS.Controls.Button.SiSButton m_cmd_update;
		internal SIS.Controls.Button.SiSButton m_cmd_insert;
		internal SIS.Controls.Button.SiSButton m_cmd_exit;
		internal SIS.Controls.Button.SiSButton m_cmd_view;
        private GroupBox groupBox1;
        private Label m_lbl_ten_bao_cao;
        private ComboBox m_cbo_don_vi_su_dung;
        private ComboBox m_cbo_don_vi_chu_quan;
        private ComboBox m_cbo_bo_tinh;
        private Label label3;
        private Label label2;
        private Label label1;
        private TextBox m_txt_loai_hinh_don_vi;
        private TextBox m_txt_ma_don_vi;
        private Label label5;
        private Label label4;
        internal SIS.Controls.Button.SiSButton m_cmd_export_excel;
        private Label label6;
        private ComboBox m_cbo_trang_thai_tai_san;
		private System.ComponentModel.IContainer components;

		public f400_bao_cao_danh_muc_o_to()
		{
			//
			// Required for Windows Form Designer support
			//
			InitializeComponent();

			//
			// TODO: Add any constructor code after InitializeComponent call
			//
			format_controls();
		}

		/// <summary>
		/// Clean up any resources being used.
		/// </summary>
		protected override void Dispose( bool disposing )
		{
			if( disposing )
			{
				if(components != null)
				{
					components.Dispose();
				}
			}
			base.Dispose( disposing );
		}

		#region Windows Form Designer generated code
		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(f400_bao_cao_danh_muc_o_to));
            this.ImageList = new System.Windows.Forms.ImageList(this.components);
            this.m_pnl_out_place_dm = new System.Windows.Forms.Panel();
            this.m_cmd_export_excel = new SIS.Controls.Button.SiSButton();
            this.m_cmd_insert = new SIS.Controls.Button.SiSButton();
            this.m_cmd_update = new SIS.Controls.Button.SiSButton();
            this.m_cmd_view = new SIS.Controls.Button.SiSButton();
            this.m_cmd_delete = new SIS.Controls.Button.SiSButton();
            this.m_cmd_exit = new SIS.Controls.Button.SiSButton();
            this.m_fg = new C1.Win.C1FlexGrid.C1FlexGrid();
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.label6 = new System.Windows.Forms.Label();
            this.m_cbo_trang_thai_tai_san = new System.Windows.Forms.ComboBox();
            this.m_txt_loai_hinh_don_vi = new System.Windows.Forms.TextBox();
            this.m_txt_ma_don_vi = new System.Windows.Forms.TextBox();
            this.label5 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.m_lbl_ten_bao_cao = new System.Windows.Forms.Label();
            this.m_cbo_don_vi_su_dung = new System.Windows.Forms.ComboBox();
            this.m_cbo_don_vi_chu_quan = new System.Windows.Forms.ComboBox();
            this.m_cbo_bo_tinh = new System.Windows.Forms.ComboBox();
            this.label3 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this.m_pnl_out_place_dm.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.m_fg)).BeginInit();
            this.groupBox1.SuspendLayout();
            this.SuspendLayout();
            // 
            // ImageList
            // 
            this.ImageList.ImageStream = ((System.Windows.Forms.ImageListStreamer)(resources.GetObject("ImageList.ImageStream")));
            this.ImageList.TransparentColor = System.Drawing.Color.Transparent;
            this.ImageList.Images.SetKeyName(0, "");
            this.ImageList.Images.SetKeyName(1, "");
            this.ImageList.Images.SetKeyName(2, "");
            this.ImageList.Images.SetKeyName(3, "");
            this.ImageList.Images.SetKeyName(4, "");
            this.ImageList.Images.SetKeyName(5, "");
            this.ImageList.Images.SetKeyName(6, "");
            this.ImageList.Images.SetKeyName(7, "");
            this.ImageList.Images.SetKeyName(8, "");
            this.ImageList.Images.SetKeyName(9, "");
            this.ImageList.Images.SetKeyName(10, "");
            this.ImageList.Images.SetKeyName(11, "");
            this.ImageList.Images.SetKeyName(12, "");
            this.ImageList.Images.SetKeyName(13, "");
            this.ImageList.Images.SetKeyName(14, "");
            this.ImageList.Images.SetKeyName(15, "");
            this.ImageList.Images.SetKeyName(16, "");
            this.ImageList.Images.SetKeyName(17, "");
            this.ImageList.Images.SetKeyName(18, "");
            this.ImageList.Images.SetKeyName(19, "");
            this.ImageList.Images.SetKeyName(20, "");
            this.ImageList.Images.SetKeyName(21, "");
            // 
            // m_pnl_out_place_dm
            // 
            this.m_pnl_out_place_dm.Controls.Add(this.m_cmd_export_excel);
            this.m_pnl_out_place_dm.Controls.Add(this.m_cmd_insert);
            this.m_pnl_out_place_dm.Controls.Add(this.m_cmd_update);
            this.m_pnl_out_place_dm.Controls.Add(this.m_cmd_view);
            this.m_pnl_out_place_dm.Controls.Add(this.m_cmd_delete);
            this.m_pnl_out_place_dm.Controls.Add(this.m_cmd_exit);
            this.m_pnl_out_place_dm.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.m_pnl_out_place_dm.Location = new System.Drawing.Point(0, 448);
            this.m_pnl_out_place_dm.Name = "m_pnl_out_place_dm";
            this.m_pnl_out_place_dm.Padding = new System.Windows.Forms.Padding(4);
            this.m_pnl_out_place_dm.Size = new System.Drawing.Size(796, 36);
            this.m_pnl_out_place_dm.TabIndex = 19;
            // 
            // m_cmd_export_excel
            // 
            this.m_cmd_export_excel.AdjustImageLocation = new System.Drawing.Point(0, 0);
            this.m_cmd_export_excel.BtnShape = SIS.Controls.Button.emunType.BtnShape.Rectangle;
            this.m_cmd_export_excel.BtnStyle = SIS.Controls.Button.emunType.XPStyle.Default;
            this.m_cmd_export_excel.Dock = System.Windows.Forms.DockStyle.Left;
            this.m_cmd_export_excel.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.m_cmd_export_excel.ImageIndex = 19;
            this.m_cmd_export_excel.ImageList = this.ImageList;
            this.m_cmd_export_excel.Location = new System.Drawing.Point(92, 4);
            this.m_cmd_export_excel.Name = "m_cmd_export_excel";
            this.m_cmd_export_excel.Size = new System.Drawing.Size(88, 28);
            this.m_cmd_export_excel.TabIndex = 22;
            this.m_cmd_export_excel.Text = "Xuất Excel";
            // 
            // m_cmd_insert
            // 
            this.m_cmd_insert.AdjustImageLocation = new System.Drawing.Point(0, 0);
            this.m_cmd_insert.BtnShape = SIS.Controls.Button.emunType.BtnShape.Rectangle;
            this.m_cmd_insert.BtnStyle = SIS.Controls.Button.emunType.XPStyle.Default;
            this.m_cmd_insert.Dock = System.Windows.Forms.DockStyle.Right;
            this.m_cmd_insert.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.m_cmd_insert.ImageIndex = 2;
            this.m_cmd_insert.ImageList = this.ImageList;
            this.m_cmd_insert.Location = new System.Drawing.Point(440, 4);
            this.m_cmd_insert.Name = "m_cmd_insert";
            this.m_cmd_insert.Size = new System.Drawing.Size(88, 28);
            this.m_cmd_insert.TabIndex = 12;
            this.m_cmd_insert.Text = "&Thêm";
            // 
            // m_cmd_update
            // 
            this.m_cmd_update.AdjustImageLocation = new System.Drawing.Point(0, 0);
            this.m_cmd_update.BtnShape = SIS.Controls.Button.emunType.BtnShape.Rectangle;
            this.m_cmd_update.BtnStyle = SIS.Controls.Button.emunType.XPStyle.Default;
            this.m_cmd_update.Dock = System.Windows.Forms.DockStyle.Right;
            this.m_cmd_update.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.m_cmd_update.ImageIndex = 3;
            this.m_cmd_update.ImageList = this.ImageList;
            this.m_cmd_update.Location = new System.Drawing.Point(528, 4);
            this.m_cmd_update.Name = "m_cmd_update";
            this.m_cmd_update.Size = new System.Drawing.Size(88, 28);
            this.m_cmd_update.TabIndex = 13;
            this.m_cmd_update.Text = "&Sửa";
            // 
            // m_cmd_view
            // 
            this.m_cmd_view.AdjustImageLocation = new System.Drawing.Point(0, 0);
            this.m_cmd_view.BtnShape = SIS.Controls.Button.emunType.BtnShape.Rectangle;
            this.m_cmd_view.BtnStyle = SIS.Controls.Button.emunType.XPStyle.Default;
            this.m_cmd_view.Dock = System.Windows.Forms.DockStyle.Left;
            this.m_cmd_view.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.m_cmd_view.ImageIndex = 18;
            this.m_cmd_view.ImageList = this.ImageList;
            this.m_cmd_view.Location = new System.Drawing.Point(4, 4);
            this.m_cmd_view.Name = "m_cmd_view";
            this.m_cmd_view.Size = new System.Drawing.Size(88, 28);
            this.m_cmd_view.TabIndex = 21;
            this.m_cmd_view.Text = "Xem";
            // 
            // m_cmd_delete
            // 
            this.m_cmd_delete.AdjustImageLocation = new System.Drawing.Point(0, 0);
            this.m_cmd_delete.BtnShape = SIS.Controls.Button.emunType.BtnShape.Rectangle;
            this.m_cmd_delete.BtnStyle = SIS.Controls.Button.emunType.XPStyle.Default;
            this.m_cmd_delete.Dock = System.Windows.Forms.DockStyle.Right;
            this.m_cmd_delete.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.m_cmd_delete.ImageIndex = 4;
            this.m_cmd_delete.ImageList = this.ImageList;
            this.m_cmd_delete.Location = new System.Drawing.Point(616, 4);
            this.m_cmd_delete.Name = "m_cmd_delete";
            this.m_cmd_delete.Size = new System.Drawing.Size(88, 28);
            this.m_cmd_delete.TabIndex = 14;
            this.m_cmd_delete.Text = "&Xoá";
            // 
            // m_cmd_exit
            // 
            this.m_cmd_exit.AdjustImageLocation = new System.Drawing.Point(0, 0);
            this.m_cmd_exit.BtnShape = SIS.Controls.Button.emunType.BtnShape.Rectangle;
            this.m_cmd_exit.BtnStyle = SIS.Controls.Button.emunType.XPStyle.Default;
            this.m_cmd_exit.Dock = System.Windows.Forms.DockStyle.Right;
            this.m_cmd_exit.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.m_cmd_exit.ImageIndex = 12;
            this.m_cmd_exit.ImageList = this.ImageList;
            this.m_cmd_exit.Location = new System.Drawing.Point(704, 4);
            this.m_cmd_exit.Name = "m_cmd_exit";
            this.m_cmd_exit.Size = new System.Drawing.Size(88, 28);
            this.m_cmd_exit.TabIndex = 11;
            this.m_cmd_exit.Text = "Thoát (Esc)";
            // 
            // m_fg
            // 
            this.m_fg.ColumnInfo = resources.GetString("m_fg.ColumnInfo");
            this.m_fg.Dock = System.Windows.Forms.DockStyle.Fill;
            this.m_fg.Location = new System.Drawing.Point(0, 150);
            this.m_fg.Name = "m_fg";
            this.m_fg.Size = new System.Drawing.Size(796, 298);
            this.m_fg.Styles = new C1.Win.C1FlexGrid.CellStyleCollection(resources.GetString("m_fg.Styles"));
            this.m_fg.TabIndex = 20;
            // 
            // groupBox1
            // 
            this.groupBox1.Controls.Add(this.label6);
            this.groupBox1.Controls.Add(this.m_cbo_trang_thai_tai_san);
            this.groupBox1.Controls.Add(this.m_txt_loai_hinh_don_vi);
            this.groupBox1.Controls.Add(this.m_txt_ma_don_vi);
            this.groupBox1.Controls.Add(this.label5);
            this.groupBox1.Controls.Add(this.label4);
            this.groupBox1.Controls.Add(this.m_lbl_ten_bao_cao);
            this.groupBox1.Controls.Add(this.m_cbo_don_vi_su_dung);
            this.groupBox1.Controls.Add(this.m_cbo_don_vi_chu_quan);
            this.groupBox1.Controls.Add(this.m_cbo_bo_tinh);
            this.groupBox1.Controls.Add(this.label3);
            this.groupBox1.Controls.Add(this.label2);
            this.groupBox1.Controls.Add(this.label1);
            this.groupBox1.Dock = System.Windows.Forms.DockStyle.Top;
            this.groupBox1.Location = new System.Drawing.Point(0, 0);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(796, 150);
            this.groupBox1.TabIndex = 21;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "Thong tin tìm kiếm";
            // 
            // label6
            // 
            this.label6.AutoSize = true;
            this.label6.Location = new System.Drawing.Point(22, 128);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(89, 13);
            this.label6.TabIndex = 12;
            this.label6.Text = "Trạng thái tài sản";
            // 
            // m_cbo_trang_thai_tai_san
            // 
            this.m_cbo_trang_thai_tai_san.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.m_cbo_trang_thai_tai_san.FormattingEnabled = true;
            this.m_cbo_trang_thai_tai_san.Location = new System.Drawing.Point(117, 123);
            this.m_cbo_trang_thai_tai_san.Name = "m_cbo_trang_thai_tai_san";
            this.m_cbo_trang_thai_tai_san.Size = new System.Drawing.Size(228, 21);
            this.m_cbo_trang_thai_tai_san.TabIndex = 11;
            // 
            // m_txt_loai_hinh_don_vi
            // 
            this.m_txt_loai_hinh_don_vi.Location = new System.Drawing.Point(736, 89);
            this.m_txt_loai_hinh_don_vi.Name = "m_txt_loai_hinh_don_vi";
            this.m_txt_loai_hinh_don_vi.Size = new System.Drawing.Size(143, 20);
            this.m_txt_loai_hinh_don_vi.TabIndex = 10;
            // 
            // m_txt_ma_don_vi
            // 
            this.m_txt_ma_don_vi.Location = new System.Drawing.Point(477, 93);
            this.m_txt_ma_don_vi.Name = "m_txt_ma_don_vi";
            this.m_txt_ma_don_vi.Size = new System.Drawing.Size(143, 20);
            this.m_txt_ma_don_vi.TabIndex = 9;
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.Location = new System.Drawing.Point(646, 95);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(83, 13);
            this.label5.TabIndex = 8;
            this.label5.Text = "Loại hình đơn vị";
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.Location = new System.Drawing.Point(399, 95);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(55, 13);
            this.label4.TabIndex = 7;
            this.label4.Text = "Mã đơn vị";
            // 
            // m_lbl_ten_bao_cao
            // 
            this.m_lbl_ten_bao_cao.Dock = System.Windows.Forms.DockStyle.Top;
            this.m_lbl_ten_bao_cao.Font = new System.Drawing.Font("Microsoft Sans Serif", 10F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.m_lbl_ten_bao_cao.Location = new System.Drawing.Point(3, 16);
            this.m_lbl_ten_bao_cao.Name = "m_lbl_ten_bao_cao";
            this.m_lbl_ten_bao_cao.Size = new System.Drawing.Size(790, 31);
            this.m_lbl_ten_bao_cao.TabIndex = 6;
            this.m_lbl_ten_bao_cao.Text = "BÁO CÁO KÊ KHAI XE Ô TÔ";
            this.m_lbl_ten_bao_cao.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // m_cbo_don_vi_su_dung
            // 
            this.m_cbo_don_vi_su_dung.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.m_cbo_don_vi_su_dung.FormattingEnabled = true;
            this.m_cbo_don_vi_su_dung.Location = new System.Drawing.Point(117, 92);
            this.m_cbo_don_vi_su_dung.Name = "m_cbo_don_vi_su_dung";
            this.m_cbo_don_vi_su_dung.Size = new System.Drawing.Size(228, 21);
            this.m_cbo_don_vi_su_dung.TabIndex = 5;
            // 
            // m_cbo_don_vi_chu_quan
            // 
            this.m_cbo_don_vi_chu_quan.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.m_cbo_don_vi_chu_quan.FormattingEnabled = true;
            this.m_cbo_don_vi_chu_quan.Location = new System.Drawing.Point(477, 50);
            this.m_cbo_don_vi_chu_quan.Name = "m_cbo_don_vi_chu_quan";
            this.m_cbo_don_vi_chu_quan.Size = new System.Drawing.Size(228, 21);
            this.m_cbo_don_vi_chu_quan.TabIndex = 4;
            // 
            // m_cbo_bo_tinh
            // 
            this.m_cbo_bo_tinh.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.m_cbo_bo_tinh.FormattingEnabled = true;
            this.m_cbo_bo_tinh.Location = new System.Drawing.Point(117, 55);
            this.m_cbo_bo_tinh.Name = "m_cbo_bo_tinh";
            this.m_cbo_bo_tinh.Size = new System.Drawing.Size(228, 21);
            this.m_cbo_bo_tinh.TabIndex = 3;
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Location = new System.Drawing.Point(32, 96);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(79, 13);
            this.label3.TabIndex = 2;
            this.label3.Text = "Đơn vị sử dụng";
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Location = new System.Drawing.Point(392, 53);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(86, 13);
            this.label2.TabIndex = 1;
            this.label2.Text = "Đơn vị chủ quản";
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(65, 58);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(46, 13);
            this.label1.TabIndex = 0;
            this.label1.Text = "Bộ/Tỉnh";
            // 
            // f400_bao_cao_danh_muc_o_to
            // 
            this.AutoScaleBaseSize = new System.Drawing.Size(5, 13);
            this.ClientSize = new System.Drawing.Size(796, 484);
            this.Controls.Add(this.m_fg);
            this.Controls.Add(this.groupBox1);
            this.Controls.Add(this.m_pnl_out_place_dm);
            this.Name = "f400_bao_cao_danh_muc_o_to";
            this.Text = "f400_bao_cao_danh_muc_o_to_de_nghi_xu_ly";
            this.Load += new System.EventHandler(this.f400_bao_cao_danh_muc_o_to_de_nghi_xu_ly_Load);
            this.m_pnl_out_place_dm.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.m_fg)).EndInit();
            this.groupBox1.ResumeLayout(false);
            this.groupBox1.PerformLayout();
            this.ResumeLayout(false);

		}
		#endregion

		#region Public Interface
		public void display(){			
			this.ShowDialog();
		}

        public void expor_excel(
            eFormMode ip_form_mode
            , string ip_str_bo_tinh
            , string ip_str_don_vi_chu_quan
            , decimal ip_dc_don_vi_su_dung
            , ref string op_str_excel_file_name) {
            //1. Đưa dữ liệu lên trên grid
                m_obj_trans = get_trans_object(m_fg);
                
                m_e_form_mode = ip_form_mode;
                US_DM_DON_VI v_us_don_vi = new US_DM_DON_VI();
                if (ip_dc_don_vi_su_dung != CONST_QLDB.ID_TAT_CA) {
                    v_us_don_vi = new US_DM_DON_VI(ip_dc_don_vi_su_dung);
                }
                else {
                    v_us_don_vi.strTEN_DON_VI = CONST_QLDB.TAT_CA;
                    v_us_don_vi.strLOAI_HINH_DON_VI = CONST_QLDB.TAT_CA;
                }
                
            //2. Xuất dữ liệu ra file excel
                CExcelWebReport v_obj_exe_report = new CExcelWebReport("BC-002 Bao cao ke khai xe o to.xls", 13, 1);;
                switch (m_e_form_mode) {
                    case eFormMode.KE_KHAI_O_TO:
                        load_data_2_grid(ip_dc_don_vi_su_dung, ID_TRANG_THAI_OTO.DANG_SU_DUNG);
                        v_obj_exe_report = new CExcelWebReport("BC-002 Bao cao ke khai xe o to.xls", 13, 1);
                        break;
                    case eFormMode.O_TO_DE_NGHI_XU_LY:
                        load_data_2_grid(ip_dc_don_vi_su_dung, ID_TRANG_THAI_OTO.DE_NGHI_XU_LY);
                        v_obj_exe_report = new CExcelWebReport("BC-005 Danh muc xe oto de nghi xu ly.xls", 13, 1);
                        break;
                    case eFormMode.O_TO_GIAO_DON_VI_SU_NGHIEP:
                        // Chỗ này đang chưa chuẩn vì chưa hiểu sự nghiệp là gì
                        load_data_2_grid(ip_dc_don_vi_su_dung, ID_TRANG_THAI_OTO.DANG_SU_DUNG);
                        v_obj_exe_report = new CExcelWebReport("BC-023 Bao cao danh muc xe o to giao cho don vi su nghiep cong lap tu chu tai chinh.xls", 13, 1);
                        break;
                    default:
                        break;
                }
               
                v_obj_exe_report.AddFindAndReplaceItem("<BO_TINH>", ip_str_bo_tinh);
                v_obj_exe_report.AddFindAndReplaceItem("<DON_VI_CHU_QUAN>", ip_str_don_vi_chu_quan);
                v_obj_exe_report.AddFindAndReplaceItem("<DON_VI_SU_DUNG_TAI_SAN>", v_us_don_vi.strTEN_DON_VI);
                v_obj_exe_report.AddFindAndReplaceItem("<MA_DON_VI>",v_us_don_vi.strMA_DON_VI);
                v_obj_exe_report.AddFindAndReplaceItem("<LOAI_HINH_DON_VI>", v_us_don_vi.strLOAI_HINH_DON_VI);

                v_obj_exe_report.FindAndReplace(false);
                v_obj_exe_report.Export2ExcelWithoutFixedRows(m_fg, 1, m_fg.Cols.Count - 1, true);
            //3. Trả về địa chỉ file
                op_str_excel_file_name = v_obj_exe_report.GetStrOutputFileNameWithPath();
        }

		#endregion

		#region Data Structure
		private enum e_col_Number{
			NGUON_GOC_XE = 10
            ,NGUON_NS = 11
            ,HD_KHAC = 17
            ,NHAN_HIEU = 2
            ,KHONG_KINH_DOANH = 16
            ,BIEN_KIEM_SOAT = 3
            ,NAM_SU_DUNG = 7
            ,NGUON_KHAC = 12
            ,CHUC_DANH_SU_DUNG = 9
            ,TEN_TAI_SAN = 1
            ,SO_CHO_NGOI = 4
            ,GIA_TRI_CON_LAI = 13
            ,NUOC_SAN_XUAT = 5
            ,QLNN = 14
            ,KINH_DOANH = 15
            ,NAM_SAN_XUAT = 6
            ,CONG_SUAT_XE = 8
            ,TEN_LOAI_TAI_SAN = 18
		}

        public enum eFormMode {
            KE_KHAI_O_TO
            , O_TO_DE_NGHI_XU_LY
            , O_TO_GIAO_DON_VI_SU_NGHIEP
        }
		#endregion

		#region Members
		ITransferDataRow m_obj_trans;		
		DS_V_DM_OTO m_ds_v_oto = new DS_V_DM_OTO();
		US_V_DM_OTO m_us_v_oto = new US_V_DM_OTO();

        eFormMode m_e_form_mode = eFormMode.KE_KHAI_O_TO;


		#endregion

		#region Private Methods
		private void format_controls(){
			CControlFormat.setFormStyle(this);
			CControlFormat.setC1FlexFormat(m_fg);
            m_fg.Cols[(int)e_col_Number.TEN_LOAI_TAI_SAN].Visible = false;            
            m_fg.Tree.Column = (int)e_col_Number.TEN_TAI_SAN;
            m_fg.Tree.Style = C1.Win.C1FlexGrid.TreeStyleFlags.SimpleLeaf;


			set_define_events();
			this.KeyPreview = true;		
		}
		private void set_initial_form_load(){						
			m_obj_trans = get_trans_object(m_fg);
            load_data_2_cbo_bo_tinh();
            load_data_2_cbo_don_vi_chu_quan();
            load_data_2_cbo_don_vi_su_dung();
            load_data_2_cbo_trang_thai_oto();


            if (m_cbo_don_vi_su_dung.SelectedValue == null) return;
            if (m_cbo_trang_thai_tai_san.SelectedValue == null) return;
			load_data_2_grid(
                CIPConvert.ToDecimal( m_cbo_don_vi_su_dung.SelectedValue)
                , CIPConvert.ToDecimal(m_cbo_trang_thai_tai_san.SelectedValue));

            
		}

        private void load_data_2_cbo_bo_tinh() {
            US_DM_DON_VI v_us_dm_don_vi = new US_DM_DON_VI();
            DS_DM_DON_VI v_ds_dm_don_vi = new DS_DM_DON_VI();

            v_us_dm_don_vi.FillDataset(v_ds_dm_don_vi, "where " + DM_DON_VI.LEVEL_MODE + " = 1");

            m_cbo_bo_tinh.DisplayMember = DM_DON_VI.TEN_DON_VI;
            m_cbo_bo_tinh.ValueMember = DM_DON_VI.ID;
            m_cbo_bo_tinh.SelectedValueChanged -= new EventHandler(m_cbo_bo_tinh_SelectedValueChanged);
            m_cbo_bo_tinh.DataSource = v_ds_dm_don_vi.DM_DON_VI;
            m_cbo_bo_tinh.SelectedValueChanged += new EventHandler(m_cbo_bo_tinh_SelectedValueChanged);
        }
        private void load_data_2_cbo_don_vi_chu_quan() {
            if (m_cbo_bo_tinh.SelectedValue == null) {
                m_cbo_don_vi_chu_quan.DataSource = null;
                m_cbo_don_vi_su_dung.DataSource = null;
                return;
            }
            US_DM_DON_VI v_us_dm_don_vi = new US_DM_DON_VI();
            DS_DM_DON_VI v_ds_dm_don_vi = new DS_DM_DON_VI();
            v_us_dm_don_vi.FillDataset(v_ds_dm_don_vi, "where " + DM_DON_VI.ID_DON_VI_CAP_TREN + " = " + CIPConvert.ToDecimal(m_cbo_bo_tinh.SelectedValue)  );

            m_cbo_don_vi_chu_quan.DisplayMember = DM_DON_VI.TEN_DON_VI;
            m_cbo_don_vi_chu_quan.ValueMember = DM_DON_VI.ID;
            m_cbo_don_vi_chu_quan.SelectedValueChanged -= new EventHandler(m_cbo_bo_tinh_SelectedValueChanged);
            m_cbo_don_vi_chu_quan.DataSource = v_ds_dm_don_vi.DM_DON_VI;
            m_cbo_don_vi_chu_quan.SelectedValueChanged += new EventHandler(m_cbo_bo_tinh_SelectedValueChanged);
        }

        private void load_data_2_cbo_don_vi_su_dung() {
            if (m_cbo_don_vi_chu_quan.SelectedValue == null) {
                m_cbo_don_vi_su_dung.DataSource = null;
                return;
            }
            US_DM_DON_VI v_us_dm_don_vi = new US_DM_DON_VI();
            DS_DM_DON_VI v_ds_dm_don_vi = new DS_DM_DON_VI();

            v_us_dm_don_vi.FillDataset(v_ds_dm_don_vi, "where " + DM_DON_VI.ID_DON_VI_CAP_TREN + " = " + CIPConvert.ToDecimal(m_cbo_don_vi_chu_quan.SelectedValue));

            m_cbo_don_vi_su_dung.DisplayMember = DM_DON_VI.TEN_DON_VI;
            m_cbo_don_vi_su_dung.ValueMember = DM_DON_VI.ID;
            m_cbo_don_vi_su_dung.SelectedValueChanged -= new EventHandler(m_cbo_bo_tinh_SelectedValueChanged);
            m_cbo_don_vi_su_dung.DataSource = v_ds_dm_don_vi.DM_DON_VI;
            m_cbo_don_vi_su_dung.SelectedValueChanged += new EventHandler(m_cbo_bo_tinh_SelectedValueChanged);
        }

        private void load_data_2_cbo_trang_thai_oto() {

            US_CM_DM_TU_DIEN v_us_cm_dm_tu_dien = new US_CM_DM_TU_DIEN();
            DS_CM_DM_TU_DIEN v_ds_cm_dm_tu_dien = new DS_CM_DM_TU_DIEN();
            v_us_cm_dm_tu_dien.fill_tu_dien_cung_loai_ds(MA_LOAI_TU_DIEN.TRANG_THAI_OTO, v_ds_cm_dm_tu_dien);
            

            m_cbo_trang_thai_tai_san.DisplayMember = CM_DM_TU_DIEN.TEN;
            m_cbo_trang_thai_tai_san.ValueMember = CM_DM_TU_DIEN.ID;
            m_cbo_trang_thai_tai_san.SelectedValueChanged -= new EventHandler(m_cbo_bo_tinh_SelectedValueChanged);
            m_cbo_trang_thai_tai_san.DataSource = v_ds_cm_dm_tu_dien.CM_DM_TU_DIEN;
            m_cbo_trang_thai_tai_san.SelectedValueChanged += new EventHandler(m_cbo_bo_tinh_SelectedValueChanged);
        }


		private ITransferDataRow get_trans_object(C1.Win.C1FlexGrid.C1FlexGrid i_fg){
			Hashtable v_htb = new Hashtable();
			v_htb.Add(V_DM_OTO.NGUON_GOC_XE, e_col_Number.NGUON_GOC_XE);
			v_htb.Add(V_DM_OTO.NGUON_NS, e_col_Number.NGUON_NS);
			v_htb.Add(V_DM_OTO.HD_KHAC, e_col_Number.HD_KHAC);
			v_htb.Add(V_DM_OTO.NHAN_HIEU, e_col_Number.NHAN_HIEU);
			v_htb.Add(V_DM_OTO.KHONG_KINH_DOANH, e_col_Number.KHONG_KINH_DOANH);
			v_htb.Add(V_DM_OTO.BIEN_KIEM_SOAT, e_col_Number.BIEN_KIEM_SOAT);
			v_htb.Add(V_DM_OTO.NAM_SU_DUNG, e_col_Number.NAM_SU_DUNG);
			v_htb.Add(V_DM_OTO.NGUON_KHAC, e_col_Number.NGUON_KHAC);
			v_htb.Add(V_DM_OTO.CHUC_DANH_SU_DUNG, e_col_Number.CHUC_DANH_SU_DUNG);
			v_htb.Add(V_DM_OTO.TEN_TAI_SAN, e_col_Number.TEN_TAI_SAN);
			v_htb.Add(V_DM_OTO.SO_CHO_NGOI, e_col_Number.SO_CHO_NGOI);
			v_htb.Add(V_DM_OTO.GIA_TRI_CON_LAI, e_col_Number.GIA_TRI_CON_LAI);
			v_htb.Add(V_DM_OTO.NUOC_SAN_XUAT, e_col_Number.NUOC_SAN_XUAT);
			v_htb.Add(V_DM_OTO.QLNN, e_col_Number.QLNN);
			v_htb.Add(V_DM_OTO.KINH_DOANH, e_col_Number.KINH_DOANH);
			v_htb.Add(V_DM_OTO.NAM_SAN_XUAT, e_col_Number.NAM_SAN_XUAT);
			v_htb.Add(V_DM_OTO.CONG_SUAT_XE, e_col_Number.CONG_SUAT_XE);
            v_htb.Add(V_DM_OTO.TEN_LOAI_TAI_SAN, e_col_Number.TEN_LOAI_TAI_SAN);


									
			ITransferDataRow v_obj_trans = new CC1TransferDataRow(i_fg,v_htb,m_ds_v_oto.V_DM_OTO.NewRow());
			return v_obj_trans;			
		}
		private void load_data_2_grid(decimal ip_dc_don_vi_su_dung, decimal ip_dc_trang_thai){
           
            m_ds_v_oto.V_DM_OTO.Clear();
            m_us_v_oto.FillDataset(ip_dc_don_vi_su_dung, ip_dc_trang_thai, m_ds_v_oto);
			m_fg.Redraw = false;
			CGridUtils.Dataset2C1Grid(m_ds_v_oto, m_fg, m_obj_trans);
            m_fg.Subtotal(C1.Win.C1FlexGrid.AggregateEnum.None
                , 0
                , (int)e_col_Number.TEN_LOAI_TAI_SAN
                , -1
                , "{0}");
			m_fg.Redraw = true;
		}

        private void export_excel() {
            CExcelReport v_obj_exe_report = new CExcelReport("BC-002 Bao cao ke khai xe o to.xls", 13, 1); ;
            switch (m_e_form_mode) {
                case eFormMode.KE_KHAI_O_TO:
                    v_obj_exe_report = new CExcelReport("BC-002 Bao cao ke khai xe o to.xls", 13, 1);
                    break;
                case eFormMode.O_TO_DE_NGHI_XU_LY:
                    v_obj_exe_report = new CExcelReport("BC-005 Danh muc xe oto de nghi xu ly.xls", 13, 1);
                    break;
                case eFormMode.O_TO_GIAO_DON_VI_SU_NGHIEP:
                    v_obj_exe_report = new CExcelReport("BC-023 Bao cao danh muc xe o to giao cho don vi su nghiep cong lap tu chu tai chinh.xls", 13, 1);
                    break;
                default:
                    break;
            }
            v_obj_exe_report.AddFindAndReplaceItem("<BO_TINH>", m_cbo_bo_tinh.Text);
            v_obj_exe_report.AddFindAndReplaceItem("<DON_VI_CHU_QUAN>", m_cbo_don_vi_chu_quan.Text);
            v_obj_exe_report.AddFindAndReplaceItem("<DON_VI_SU_DUNG_TAI_SAN>", m_cbo_don_vi_su_dung.Text);
            v_obj_exe_report.AddFindAndReplaceItem("<MA_DON_VI>", m_txt_ma_don_vi.Text);
            v_obj_exe_report.AddFindAndReplaceItem("<LOAI_HINH_DON_VI>", m_txt_loai_hinh_don_vi.Text);

            v_obj_exe_report.FindAndReplace(false);
            v_obj_exe_report.Export2ExcelWithoutFixedRows(m_fg, 1, m_fg.Cols.Count - 1, true);
        }
		private void grid2us_object(US_V_DM_OTO i_us
			, int i_grid_row) {
			DataRow v_dr;
			v_dr = (DataRow) m_fg.Rows[i_grid_row].UserData;
			m_obj_trans.GridRow2DataRow(i_grid_row,v_dr);
			i_us.DataRow2Me(v_dr);
		}

	
		private void us_object2grid(US_V_DM_OTO i_us
			, int i_grid_row) {
			DataRow v_dr = (DataRow) m_fg.Rows[i_grid_row].UserData;
			i_us.Me2DataRow(v_dr);
			m_obj_trans.DataRow2GridRow(v_dr, i_grid_row);
		}


		private void insert_v_dm_oto(){			
		//	f400_bao_cao_danh_muc_o_to_de_nghi_xu_ly_DE v_fDE = new  f400_bao_cao_danh_muc_o_to_de_nghi_xu_ly_DE();								
		//	v_fDE.display();
			//load_data_2_grid();
		}

		private void update_v_dm_oto(){			
			if (!CGridUtils.IsThere_Any_NonFixed_Row(m_fg)) return;
			if (!CGridUtils.isValid_NonFixed_RowIndex(m_fg, m_fg.Row)) return;			
			grid2us_object(m_us_v_oto, m_fg.Row);
		//	f400_bao_cao_danh_muc_o_to_de_nghi_xu_ly_DE v_fDE = new f400_bao_cao_danh_muc_o_to_de_nghi_xu_ly_DE();
		//	v_fDE.display(m_us);
			//load_data_2_grid();
		}
				
		private void delete_v_dm_oto(){
			if (!CGridUtils.IsThere_Any_NonFixed_Row(m_fg)) return;
			if (!CGridUtils.isValid_NonFixed_RowIndex(m_fg, m_fg.Row)) return;
			if (BaseMessages.askUser_DataCouldBeDeleted(8) != BaseMessages.IsDataCouldBeDeleted.CouldBeDeleted)  return;
			US_V_DM_OTO v_us = new US_V_DM_OTO();
			grid2us_object(v_us, m_fg.Row);
			try {			
				v_us.BeginTransaction();    											
				v_us.Delete();                      								
				v_us.CommitTransaction();
				m_fg.Rows.Remove(m_fg.Row);				
			}
			catch (Exception v_e) {
				v_us.Rollback();
				CDBExceptionHandler v_objErrHandler = new CDBExceptionHandler(v_e,
					new CDBClientDBExceptionInterpret());
				v_objErrHandler.showErrorMessage();
			}
		}

		private void view_v_dm_oto(){			
			if (!CGridUtils.IsThere_Any_NonFixed_Row(m_fg)) return;
			if (!CGridUtils.isValid_NonFixed_RowIndex(m_fg, m_fg.Row)) return;
			grid2us_object(m_us_v_oto, m_fg.Row);
		//	f400_bao_cao_danh_muc_o_to_de_nghi_xu_ly_DE v_fDE = new f400_bao_cao_danh_muc_o_to_de_nghi_xu_ly_DE();			
		//	v_fDE.display(m_us);
		}

        #endregion
        private void set_define_events(){
			m_cmd_exit.Click += new EventHandler(m_cmd_exit_Click);
			m_cmd_insert.Click += new EventHandler(m_cmd_insert_Click);
			m_cmd_update.Click += new EventHandler(m_cmd_update_Click);
			m_cmd_delete.Click += new EventHandler(m_cmd_delete_Click);
			m_cmd_view.Click += new EventHandler(m_cmd_view_Click);

            m_cmd_export_excel.Click += new EventHandler(m_cmd_export_excel_Click);
            m_cbo_bo_tinh.SelectedValueChanged += new EventHandler(m_cbo_bo_tinh_SelectedValueChanged);
            m_cbo_don_vi_chu_quan.SelectedValueChanged += new EventHandler(m_cbo_don_vi_chu_quan_SelectedValueChanged);
            m_cbo_don_vi_su_dung.SelectedValueChanged += new EventHandler(m_cbo_don_vi_su_dung_SelectedValueChanged);
            m_cbo_trang_thai_tai_san.SelectedValueChanged += new EventHandler(m_cbo_trang_thai_tai_san_SelectedValueChanged);

		}

        void m_cbo_trang_thai_tai_san_SelectedValueChanged(object sender, EventArgs e) {
            try {

                if (m_cbo_trang_thai_tai_san.SelectedValue == null) return;
                if (m_cbo_don_vi_su_dung.SelectedValue == null) return;

                load_data_2_grid(
                    CIPConvert.ToDecimal( m_cbo_don_vi_su_dung.SelectedValue)
                    , CIPConvert.ToDecimal(m_cbo_trang_thai_tai_san.SelectedValue));
            }
            catch (Exception v_e) {
                
                CSystemLog_301.ExceptionHandle(v_e);
            }
        }

        void m_cmd_export_excel_Click(object sender, EventArgs e) {
            try {
                export_excel();
            }
            catch (Exception v_e) {
                
                CSystemLog_301.ExceptionHandle(v_e);
            }
        }

        void m_cbo_don_vi_chu_quan_SelectedValueChanged(object sender, EventArgs e) {
            try {
                load_data_2_cbo_don_vi_su_dung();
                if (m_cbo_don_vi_su_dung.SelectedValue == null) return;
                if (m_cbo_trang_thai_tai_san.SelectedValue == null) return;
                load_data_2_grid(
                    CIPConvert.ToDecimal(m_cbo_don_vi_su_dung.SelectedValue)
                    , CIPConvert.ToDecimal(m_cbo_trang_thai_tai_san.SelectedValue));
            }
            catch (Exception v_e) {
                
                CSystemLog_301.ExceptionHandle(v_e);
            }
        }

        void m_cbo_don_vi_su_dung_SelectedValueChanged(object sender, EventArgs e) {
            try {
                if (m_cbo_don_vi_su_dung.SelectedValue == null) return;


                US_DM_DON_VI v_us_dm_don_vi = new US_DM_DON_VI(CIPConvert.ToDecimal(m_cbo_don_vi_su_dung.SelectedValue));

                m_txt_loai_hinh_don_vi.Text = v_us_dm_don_vi.strLOAI_HINH_DON_VI;
                m_txt_ma_don_vi.Text = v_us_dm_don_vi.strMA_DON_VI;

                
                if (m_cbo_trang_thai_tai_san.SelectedValue == null) return;
                load_data_2_grid(
                    CIPConvert.ToDecimal(m_cbo_don_vi_su_dung.SelectedValue)
                    , CIPConvert.ToDecimal(m_cbo_trang_thai_tai_san.SelectedValue));

            }
            catch (Exception v_e) {
                
                CSystemLog_301.ExceptionHandle(v_e);
            }
        }

     

        void m_cbo_bo_tinh_SelectedValueChanged(object sender, EventArgs e) {
            try {
                load_data_2_cbo_don_vi_chu_quan();
                load_data_2_cbo_don_vi_su_dung();
                if (m_cbo_don_vi_su_dung.SelectedValue == null) return;
                if (m_cbo_trang_thai_tai_san.SelectedValue == null) return;
                load_data_2_grid(
                    CIPConvert.ToDecimal(m_cbo_don_vi_su_dung.SelectedValue)
                    , CIPConvert.ToDecimal(m_cbo_trang_thai_tai_san.SelectedValue));

            }
            catch (Exception v_e) {
                
                CSystemLog_301.ExceptionHandle(v_e);
            }
        }
		

//
		//
		//		EVENT HANLDERS
		//
		//
		private void f400_bao_cao_danh_muc_o_to_de_nghi_xu_ly_Load(object sender, System.EventArgs e) {
			try{
				set_initial_form_load();
			}
			catch (Exception v_e){
				CSystemLog_301.ExceptionHandle(v_e);
			}
		
		}

		private void m_cmd_exit_Click(object sender, EventArgs e) {
			try{
				this.Close();
			}
			catch (Exception v_e){
				CSystemLog_301.ExceptionHandle(v_e);
			}
		}

		private void m_cmd_insert_Click(object sender, EventArgs e) {
			try{
				insert_v_dm_oto();
			}
			catch (Exception v_e){
				CSystemLog_301.ExceptionHandle(v_e);
			}
		}

		private void m_cmd_update_Click(object sender, EventArgs e) {
			try{
				update_v_dm_oto();
			}
			catch (Exception v_e){
				CSystemLog_301.ExceptionHandle(v_e);
			}
		}

		private void m_cmd_delete_Click(object sender, EventArgs e) {
			try{
				delete_v_dm_oto();
			}
			catch (Exception v_e){
				CSystemLog_301.ExceptionHandle(v_e);
			}
		}

		private void m_cmd_view_Click(object sender, EventArgs e) {
			try{
				view_v_dm_oto();
			}
			catch (Exception v_e){
				CSystemLog_301.ExceptionHandle(v_e);
			}
		}

	}
}

