///************************************************
/// Generated by: linhdh
/// Date: 20/10/2011 03:48:10
/// Goal: Create User Service Class for V_DM_NOI_DUNG_THANH_TOAN
///************************************************
/// <summary>
/// Create User Service Class for V_DM_NOI_DUNG_THANH_TOAN
/// </summary>

using System;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;
using WebDS;


namespace WebUS{

public class US_V_DM_NOI_DUNG_THANH_TOAN : US_Object
{
	private const string c_TableName = "V_DM_NOI_DUNG_THANH_TOAN";
#region "Public Properties"
	public decimal dcID 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID"] = value;
		}
	}

	public bool IsIDNull()	{
		return pm_objDR.IsNull("ID");
	}

	public void SetIDNull() {
		pm_objDR["ID"] = System.Convert.DBNull;
	}

	public string strTEN_NOI_DUNG 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "TEN_NOI_DUNG", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["TEN_NOI_DUNG"] = value;
		}
	}

	public bool IsTEN_NOI_DUNGNull() 
	{
		return pm_objDR.IsNull("TEN_NOI_DUNG");
	}

	public void SetTEN_NOI_DUNGNull() {
		pm_objDR["TEN_NOI_DUNG"] = System.Convert.DBNull;
	}

	public string strGHI_CHU 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "GHI_CHU", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["GHI_CHU"] = value;
		}
	}

	public bool IsGHI_CHUNull() 
	{
		return pm_objDR.IsNull("GHI_CHU");
	}

	public void SetGHI_CHUNull() {
		pm_objDR["GHI_CHU"] = System.Convert.DBNull;
	}

	public decimal dcID_LOAI_HOP_DONG 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_LOAI_HOP_DONG", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_LOAI_HOP_DONG"] = value;
		}
	}

	public bool IsID_LOAI_HOP_DONGNull()	{
		return pm_objDR.IsNull("ID_LOAI_HOP_DONG");
	}

	public void SetID_LOAI_HOP_DONGNull() {
		pm_objDR["ID_LOAI_HOP_DONG"] = System.Convert.DBNull;
	}

	public string strMA_DON_VI_TINH 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "MA_DON_VI_TINH", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["MA_DON_VI_TINH"] = value;
		}
	}

	public bool IsMA_DON_VI_TINHNull() 
	{
		return pm_objDR.IsNull("MA_DON_VI_TINH");
	}

	public void SetMA_DON_VI_TINHNull() {
		pm_objDR["MA_DON_VI_TINH"] = System.Convert.DBNull;
	}

	public decimal dcDON_GIA_DEFAULT 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "DON_GIA_DEFAULT", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["DON_GIA_DEFAULT"] = value;
		}
	}

	public bool IsDON_GIA_DEFAULTNull()	{
		return pm_objDR.IsNull("DON_GIA_DEFAULT");
	}

	public void SetDON_GIA_DEFAULTNull() {
		pm_objDR["DON_GIA_DEFAULT"] = System.Convert.DBNull;
	}

	public string strMA_TAN_SUAT 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "MA_TAN_SUAT", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["MA_TAN_SUAT"] = value;
		}
	}

	public bool IsMA_TAN_SUATNull() 
	{
		return pm_objDR.IsNull("MA_TAN_SUAT");
	}

	public void SetMA_TAN_SUATNull() {
		pm_objDR["MA_TAN_SUAT"] = System.Convert.DBNull;
	}

	public string strHOC_LIEU_YN 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "HOC_LIEU_YN", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["HOC_LIEU_YN"] = value;
		}
	}

	public bool IsHOC_LIEU_YNNull() 
	{
		return pm_objDR.IsNull("HOC_LIEU_YN");
	}

	public void SetHOC_LIEU_YNNull() {
		pm_objDR["HOC_LIEU_YN"] = System.Convert.DBNull;
	}

	public string strVAN_HANH_YN 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "VAN_HANH_YN", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["VAN_HANH_YN"] = value;
		}
	}

	public bool IsVAN_HANH_YNNull() 
	{
		return pm_objDR.IsNull("VAN_HANH_YN");
	}

	public void SetVAN_HANH_YNNull() {
		pm_objDR["VAN_HANH_YN"] = System.Convert.DBNull;
	}

	public decimal dcSO_LUONG_HE_SO_DEFAULT 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "SO_LUONG_HE_SO_DEFAULT", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["SO_LUONG_HE_SO_DEFAULT"] = value;
		}
	}

	public bool IsSO_LUONG_HE_SO_DEFAULTNull()	{
		return pm_objDR.IsNull("SO_LUONG_HE_SO_DEFAULT");
	}

	public void SetSO_LUONG_HE_SO_DEFAULTNull() {
		pm_objDR["SO_LUONG_HE_SO_DEFAULT"] = System.Convert.DBNull;
	}

	public string strDON_VI_TINH 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "DON_VI_TINH", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["DON_VI_TINH"] = value;
		}
	}

	public bool IsDON_VI_TINHNull() 
	{
		return pm_objDR.IsNull("DON_VI_TINH");
	}

	public void SetDON_VI_TINHNull() {
		pm_objDR["DON_VI_TINH"] = System.Convert.DBNull;
	}

	public string strTAN_SUAT 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "TAN_SUAT", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["TAN_SUAT"] = value;
		}
	}

	public bool IsTAN_SUATNull() 
	{
		return pm_objDR.IsNull("TAN_SUAT");
	}

	public void SetTAN_SUATNull() {
		pm_objDR["TAN_SUAT"] = System.Convert.DBNull;
	}

	public string strMA_TU_DIEN 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "MA_TU_DIEN", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["MA_TU_DIEN"] = value;
		}
	}

	public bool IsMA_TU_DIENNull() 
	{
		return pm_objDR.IsNull("MA_TU_DIEN");
	}

	public void SetMA_TU_DIENNull() {
		pm_objDR["MA_TU_DIEN"] = System.Convert.DBNull;
	}

	public string strTEN_NGAN 
	{
		get 
		{
			return CNull.RowNVLString(pm_objDR, "TEN_NGAN", IPConstants.c_DefaultString);
		}
		set 
		{
			pm_objDR["TEN_NGAN"] = value;
		}
	}

	public bool IsTEN_NGANNull() 
	{
		return pm_objDR.IsNull("TEN_NGAN");
	}

	public void SetTEN_NGANNull() {
		pm_objDR["TEN_NGAN"] = System.Convert.DBNull;
	}


    public string strSU_KIEN_YN
    {
        get
        {
            return CNull.RowNVLString(pm_objDR, "SU_KIEN_YN", IPConstants.c_DefaultString);
        }
        set
        {
            pm_objDR["SU_KIEN_YN"] = value;
        }
    }

    public bool IsSU_KIEN_YNNull()
    {
        return pm_objDR.IsNull("SU_KIEN_YN");
    }

    public void SetSU_KIEN_YNNull()
    {
        pm_objDR["SU_KIEN_YN"] = System.Convert.DBNull;
    }

    public string strSU_DUNG_YN
    {
        get
        {
            return CNull.RowNVLString(pm_objDR, "SU_DUNG_YN", IPConstants.c_DefaultString);
        }
        set
        {
            pm_objDR["SU_DUNG_YN"] = value;
        }
    }

    public bool IsSU_DUNG_YNNull()
    {
        return pm_objDR.IsNull("SU_DUNG_YN");
    }

    public void SetSU_DUNG_YNNull()
    {
        pm_objDR["SU_DUNG_YN"] = System.Convert.DBNull;
    }
#endregion
#region "Init Functions"
	public US_V_DM_NOI_DUNG_THANH_TOAN() 
	{
		pm_objDS = new DS_V_DM_NOI_DUNG_THANH_TOAN();
		pm_strTableName = c_TableName;
		pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
	}

	public US_V_DM_NOI_DUNG_THANH_TOAN(DataRow i_objDR): this()
	{
		this.DataRow2Me(i_objDR);
	}

	public US_V_DM_NOI_DUNG_THANH_TOAN(decimal i_dbID) 
	{
		pm_objDS = new DS_V_DM_NOI_DUNG_THANH_TOAN();
		pm_strTableName = c_TableName;
		IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
		v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
		SqlCommand v_cmdSQL;
		v_cmdSQL = v_objMkCmd.getSelectCmd();
		this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
		pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
	}
#endregion
	}
}
