///************************************************
/// Generated by: TuDM
/// Date: 26/08/2013 09:03:49
/// Goal: Create User Service Class for V_BC_THHTSD_NHA_DAT
///************************************************
/// <summary>
/// Create User Service Class for V_BC_THHTSD_NHA_DAT
/// </summary>

using System;
using WebDS;
using IP.Core.IPCommon;
using IP.Core.IPUserService;
using System.Data.SqlClient;
using System.Data;
using WebDS;


namespace AuctionUS{

public class US_V_BC_THHTSD_NHA_DAT : US_Object
{
	private const string c_TableName = "V_BC_THHTSD_NHA_DAT";
#region "Public Properties"
	public decimal dcID_DON_VI_SU_DUNG 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_DON_VI_SU_DUNG", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_DON_VI_SU_DUNG"] = value;
		}
	}

	public bool IsID_DON_VI_SU_DUNGNull()	{
		return pm_objDR.IsNull("ID_DON_VI_SU_DUNG");
	}

	public void SetID_DON_VI_SU_DUNGNull() {
		pm_objDR["ID_DON_VI_SU_DUNG"] = System.Convert.DBNull;
	}

	public decimal dcID_DON_VI_CHU_QUAN 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_DON_VI_CHU_QUAN", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_DON_VI_CHU_QUAN"] = value;
		}
	}

	public bool IsID_DON_VI_CHU_QUANNull()	{
		return pm_objDR.IsNull("ID_DON_VI_CHU_QUAN");
	}

	public void SetID_DON_VI_CHU_QUANNull() {
		pm_objDR["ID_DON_VI_CHU_QUAN"] = System.Convert.DBNull;
	}

	public decimal dcID_LOAI_TAI_SAN 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_LOAI_TAI_SAN", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_LOAI_TAI_SAN"] = value;
		}
	}

	public bool IsID_LOAI_TAI_SANNull()	{
		return pm_objDR.IsNull("ID_LOAI_TAI_SAN");
	}

	public void SetID_LOAI_TAI_SANNull() {
		pm_objDR["ID_LOAI_TAI_SAN"] = System.Convert.DBNull;
	}

	public decimal dcID_TRANG_THAI 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_TRANG_THAI", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_TRANG_THAI"] = value;
		}
	}

	public bool IsID_TRANG_THAINull()	{
		return pm_objDR.IsNull("ID_TRANG_THAI");
	}

	public void SetID_TRANG_THAINull() {
		pm_objDR["ID_TRANG_THAI"] = System.Convert.DBNull;
	}

	public decimal dcID_TINH_TRANG 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "ID_TINH_TRANG", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["ID_TINH_TRANG"] = value;
		}
	}

	public bool IsID_TINH_TRANGNull()	{
		return pm_objDR.IsNull("ID_TINH_TRANG");
	}

	public void SetID_TINH_TRANGNull() {
		pm_objDR["ID_TINH_TRANG"] = System.Convert.DBNull;
	}

	public decimal dcSO_LUONG 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "SO_LUONG", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["SO_LUONG"] = value;
		}
	}

	public bool IsSO_LUONGNull()	{
		return pm_objDR.IsNull("SO_LUONG");
	}

	public void SetSO_LUONGNull() {
		pm_objDR["SO_LUONG"] = System.Convert.DBNull;
	}

	public decimal dcDT_KHUON_VIEN 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "DT_KHUON_VIEN", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["DT_KHUON_VIEN"] = value;
		}
	}

	public bool IsDT_KHUON_VIENNull()	{
		return pm_objDR.IsNull("DT_KHUON_VIEN");
	}

	public void SetDT_KHUON_VIENNull() {
		pm_objDR["DT_KHUON_VIEN"] = System.Convert.DBNull;
	}

	public decimal dcDT_TRU_SO_LAM_VIEC 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "DT_TRU_SO_LAM_VIEC", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["DT_TRU_SO_LAM_VIEC"] = value;
		}
	}

	public bool IsDT_TRU_SO_LAM_VIECNull()	{
		return pm_objDR.IsNull("DT_TRU_SO_LAM_VIEC");
	}

	public void SetDT_TRU_SO_LAM_VIECNull() {
		pm_objDR["DT_TRU_SO_LAM_VIEC"] = System.Convert.DBNull;
	}

	public decimal dcDT_CO_SO_HOAT_DONG_SU_NGHIEP 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "DT_CO_SO_HOAT_DONG_SU_NGHIEP", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["DT_CO_SO_HOAT_DONG_SU_NGHIEP"] = value;
		}
	}

	public bool IsDT_CO_SO_HOAT_DONG_SU_NGHIEPNull()	{
		return pm_objDR.IsNull("DT_CO_SO_HOAT_DONG_SU_NGHIEP");
	}

	public void SetDT_CO_SO_HOAT_DONG_SU_NGHIEPNull() {
		pm_objDR["DT_CO_SO_HOAT_DONG_SU_NGHIEP"] = System.Convert.DBNull;
	}

	public decimal dcDT_LAM_NHA_O 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "DT_LAM_NHA_O", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["DT_LAM_NHA_O"] = value;
		}
	}

	public bool IsDT_LAM_NHA_ONull()	{
		return pm_objDR.IsNull("DT_LAM_NHA_O");
	}

	public void SetDT_LAM_NHA_ONull() {
		pm_objDR["DT_LAM_NHA_O"] = System.Convert.DBNull;
	}

	public decimal dcDT_CHO_THUE 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "DT_CHO_THUE", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["DT_CHO_THUE"] = value;
		}
	}

	public bool IsDT_CHO_THUENull()	{
		return pm_objDR.IsNull("DT_CHO_THUE");
	}

	public void SetDT_CHO_THUENull() {
		pm_objDR["DT_CHO_THUE"] = System.Convert.DBNull;
	}

	public decimal dcDT_BO_TRONG 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "DT_BO_TRONG", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["DT_BO_TRONG"] = value;
		}
	}

	public bool IsDT_BO_TRONGNull()	{
		return pm_objDR.IsNull("DT_BO_TRONG");
	}

	public void SetDT_BO_TRONGNull() {
		pm_objDR["DT_BO_TRONG"] = System.Convert.DBNull;
	}

	public decimal dcDT_BI_LAN_CHIEM 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "DT_BI_LAN_CHIEM", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["DT_BI_LAN_CHIEM"] = value;
		}
	}

	public bool IsDT_BI_LAN_CHIEMNull()	{
		return pm_objDR.IsNull("DT_BI_LAN_CHIEM");
	}

	public void SetDT_BI_LAN_CHIEMNull() {
		pm_objDR["DT_BI_LAN_CHIEM"] = System.Convert.DBNull;
	}

	public decimal dcDT_SU_DUNG_MUC_DICH_KHAC 
	{
		get
		{
			return CNull.RowNVLDecimal(pm_objDR, "DT_SU_DUNG_MUC_DICH_KHAC", IPConstants.c_DefaultDecimal);
		}
		set	
		{
			pm_objDR["DT_SU_DUNG_MUC_DICH_KHAC"] = value;
		}
	}

	public bool IsDT_SU_DUNG_MUC_DICH_KHACNull()	{
		return pm_objDR.IsNull("DT_SU_DUNG_MUC_DICH_KHAC");
	}

	public void SetDT_SU_DUNG_MUC_DICH_KHACNull() {
		pm_objDR["DT_SU_DUNG_MUC_DICH_KHAC"] = System.Convert.DBNull;
	}

#endregion
#region "Init Functions"
	public US_V_BC_THHTSD_NHA_DAT() 
	{
		pm_objDS = new DS_V_BC_THHTSD_NHA_DAT();
		pm_strTableName = c_TableName;
		pm_objDR = pm_objDS.Tables[pm_strTableName].NewRow();
	}

	public US_V_BC_THHTSD_NHA_DAT(DataRow i_objDR): this()
	{
		this.DataRow2Me(i_objDR);
	}

	public US_V_BC_THHTSD_NHA_DAT(decimal i_dbID) 
	{
		pm_objDS = new DS_V_BC_THHTSD_NHA_DAT();
		pm_strTableName = c_TableName;
		IMakeSelectCmd v_objMkCmd = new CMakeAndSelectCmd(pm_objDS, c_TableName);
		v_objMkCmd.AddCondition("ID", i_dbID, eKieuDuLieu.KieuNumber, eKieuSoSanh.Bang);
		SqlCommand v_cmdSQL;
		v_cmdSQL = v_objMkCmd.getSelectCmd();
		this.FillDatasetByCommand(pm_objDS, v_cmdSQL);
		pm_objDR = getRowClone(pm_objDS.Tables[pm_strTableName].Rows[0]);
	}
#endregion
	}
}
